# Generated by Django 3.1.6 on 2021-05-01 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210501_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
